export const Images = {
    Blocker: new URL('./assets/1Blocker.png' , import.meta.url).href,
    Alva: new URL('./assets/Alva.png',  import.meta.url).href,
    AndroidStudio: new URL('./assets/AndroidStudio.png', import.meta.url).href,
    AppleTv: new URL('./assets/AppleTv.png' , import.meta.url).href,
    AppStore: new URL('./assets/AppStore.png' , import.meta.url).href,
    Arc: new URL('./assets/Arc.png' , import.meta.url).href,
    Bloody: new URL('./assets/Bloody7.png' , import.meta.url).href,
    blyOS: new URL('./assets/blyOS.png' , import.meta.url).href,
    Calculator: new URL('./assets/Calculator.png' , import.meta.url).href,
    Calendar: new URL('./assets/Calendar.png' , import.meta.url).href,
    Chrome: new URL('./assets/Chrome.png' , import.meta.url).href,
    Contact: new URL('./assets/Contacts.png' , import.meta.url).href,
    Discord: new URL('./assets/Discord.png' , import.meta.url).href,
    Docker: new URL('./assets/Docker.png' , import.meta.url).href,
    Earth: new URL('./assets/Earth.png' , import.meta.url).href,
    FaceTime: new URL('./assets/FaceTime.png' , import.meta.url).href,
    FanControl: new URL('./assets/FanControl.png' , import.meta.url).href,
    Finder: new URL('./assets/Finder.png' , import.meta.url).href,
    Folder: new URL('./assets/Folder.png' , import.meta.url).href,
    GitHub: new URL('./assets/GitHub.png' , import.meta.url).href,
    Gmail: new URL('./assets/Gmail.png' , import.meta.url).href,
    Google: new URL('./assets/Google.png' , import.meta.url).href,
    Idena: new URL('./assets/Idena.png' , import.meta.url).href,
    Instagram: new URL('./assets/Instagram.png' , import.meta.url).href,
    JetBrains: new URL('./assets/JetBrains.png' , import.meta.url).href,
    Keep: new URL('./assets/Keep.png' , import.meta.url).href,
    LanScan: new URL('./assets/LanScan.png' , import.meta.url).href,
    LaunchPad: new URL('./assets/LaunchPad.png' , import.meta.url).href,
    Map: new URL('./assets/Map.png' , import.meta.url).href,
    Message: new URL('./assets/Message.png' , import.meta.url).href,
    Music: new URL('./assets/Music.png' , import.meta.url).href,
    Netflix: new URL('./assets/Netflix.png' , import.meta.url).href,
    Node: new URL('./assets/Node.png' , import.meta.url).href,
    Phone: new URL('./assets/Phone.png' , import.meta.url).href,
    Podcasts: new URL('./assets/Podcasts.png' , import.meta.url).href,
    PyCharm: new URL('./assets/PyCharm.png' , import.meta.url).href,
    Safari: new URL('./assets/Safari.png' , import.meta.url).href,
    Settings: new URL('./assets/Settings.png' , import.meta.url).href,
    Spotify: new URL('./assets/Spotify.png' , import.meta.url).href,
    Steam: new URL('./assets/Steam.png' , import.meta.url).href,
    Sublime: new URL('./assets/Sublime.png' , import.meta.url).href,
    Telegram: new URL('./assets/Telegram.png' , import.meta.url).href,
    Terminal: new URL('./assets/Terminal.png' , import.meta.url).href,
    Trash: new URL('./assets/Trash.png' , import.meta.url).href,
    VCL: new URL('./assets/VCL.png' , import.meta.url).href,
    VScode: new URL('./assets/VScode.png' , import.meta.url).href,
    WebTorrent: new URL('./assets/WebTorrent.png' , import.meta.url).href,
    WhatApp: new URL('./assets/WhatApp.png' , import.meta.url).href,
    Word: new URL('./assets/Word.png' , import.meta.url).href,
    XBox: new URL('./assets/XBox.png' , import.meta.url).href,
    YouTube: new URL('./assets/YouTube.png', import.meta.url).href,
    apple: new URL('./assets/apple.svg', import.meta.url).href,
    battery: new URL('./assets/battery.svg', import.meta.url).href,
    wifi: new URL('./assets/wifi1.svg', import.meta.url).href,
    bg: new URL('./assets/bg.jpg', import.meta.url).href,
    pencil: new URL('./assets/pencil.svg', import.meta.url).href,
    logOut: new URL('./assets/log-out.svg', import.meta.url).href,
 
}